### ISSUE TITLE
Very Quick Calls Generate the Same ID

### ISSUE THREAD

**Issue by Ellisande** [ongteckwu/typeid-ts#1]
Hi! Not sure if you are using Github issues for this, but I was trying out the project and found that calling `generateNew("prefix")` quickly generates the same ID, and I was wondering if this was intentional? I can get around it by using `encodeFromUUID` and generating a UUID, but it looks like I lose the locality.

```ts
// Example code
  new Array(30).fill(0).map((_, i) => {
    console.log(generateNew("knot"));
  });
```

```bash
Example Output:
knot_1g64w3jc9g6gs2tchncdjjtdsk
knot_1g64w3jc9g6gs2tchncdjjtdsk
knot_1g64w3jc9g6gs2tchncdk2tdsk
knot_1g64w3jc9g6gs2tchncdk2tdsk
knot_1g64w3jc9g6gs2tchncdk2tdsk
knot_1g64w3jc9g6gs2tchncdk2tdsk
knot_1g64w3jc9g6gs2tchncdk2tdsk
knot_1g64w3jc9g6gs2tchncdk2tdsk
knot_1g64w3jc9g6gs2tchncgr2tdsq
knot_1g64w3jc9g6gs2tchncgr2tdsq
knot_1g64w3jc9g6gs2tchncgr2tdsq
knot_1g64w3jc9g6gs2tchncgr2tdsq
knot_1g64w3jc9g6gs2tchncgrjtdv3
knot_1g64w3jc9g6gs2tchncgrjtdv3
knot_1g64w3jc9g6gs2tchncgrjtdv3
knot_1g64w3jc9g6gs2tchncgrjtdv3
knot_1g64w3jc9g6gs2tchncgrjtdv3
knot_1g64w3jc9g6gs2tchncgs2tdv3
knot_1g64w3jc9g6gs2tchncgs2tdv3
knot_1g64w3jc9g6gs2tchncgs2tdv3
knot_1g64w3jc9g6gs2tchncgs2tdv3
knot_1g64w3jc9g6gs2tchncgs2tdv3
knot_1g64w3jc9g6gs2tchncgs2tdv3
knot_1g64w3jc9g6gs2tchncgs2tdv3
knot_1g64w3jc9g6gs2tchncgs2tdv3
knot_1g64w3jc9g6gs2tchncgs2tdv3
knot_1g64w3jc9g6gs2tchncgs2tdv3
knot_1g64w3jc9g6gs2tchncgs2tdv3
knot_1g64w3jc9g6gs2tchncgs2tdv3
knot_1g64w3jc9g6gs2tchncgs2tdv3
```

**Comment by ongteckwu** [comment]
Hi Ellisande,

Thanks for discovering this. I think it could be the uuidv7 generator that I am using. Let me try fixing it!

**Comment by ongteckwu** [comment]
I think the UUID slow down might be intentional since its introduced in later versions. I will have to downgrade to uuidv7 v0.4.4 and test.

**Comment by ongteckwu** [comment]
Ok I fixed it. It's not the uuidv7 package, it's the byte conversion code. You can update to v0.2.3 now for the change :D

**Comment by Ellisande** [comment]
Whoa, thanks for the fast turn around!
