### ISSUE TITLE
Node version requirements too strict?

### ISSUE THREAD

**Issue by DanHulton** [ongteckwu/typeid-ts#2]
It looks like the node version requirements for this package are restricted to just the latest LTS:
```
"node": ">= 18.12 <19"
```
Is there some reason for this restriction, i.e. does it not work under older or newer versions of Node?  Sure, folks should generally want to be on the latest-available LTS, but actually making that decision should be done by the implementer of the requesting package, unless there's reason why this package wouldn't work under any other node range requirement.

**Comment by ongteckwu** [comment]
You are right. I will remove it. Thanks for noticing Dan!

**Comment by ongteckwu** [comment]
@DanHulton removed in v0.2.4.
